# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pr: none

resources:
  repositories:
    - repository: alm1
      type: git
      name: ACRRepro/test
  
    - repository: alm2
      type: git
      name: ACRRepro/ACRRepro



pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

